export type ConnectorApp = {
  id: string;
  name: string;
  category: string;
  emoji: string;
  fields: string[];
  how: string;
};

const f = {
  key: ["API key"],
  oauth: ["OAuth login"],
  token: ["Access token"],
  keySecret: ["API key", "API secret"],
  webhook: ["Webhook URL", "Signing secret"],
};

function app(
  id: string,
  name: string,
  category: string,
  emoji: string,
  fields: string[],
  how: string,
): ConnectorApp {
  return { id, name, category, emoji, fields, how };
}

export const CONNECTORS: ConnectorApp[] = [
  app(
    "google-search",
    "Google Search",
    "Search & Data",
    "🔎",
    f.key,
    "Gives the AI live web results before it answers.",
  ),
  app(
    "firecrawl",
    "Firecrawl",
    "Search & Data",
    "🔥",
    f.key,
    "Crawl and scrape any website for live AI context.",
  ),
  app(
    "gmail",
    "Gmail",
    "Communication",
    "✉️",
    f.oauth,
    "Read, draft and send email on your behalf.",
  ),
  app(
    "google-calendar",
    "Google Calendar",
    "Productivity",
    "📅",
    f.oauth,
    "Create and move events from a prompt.",
  ),
  app("google-drive", "Google Drive", "Storage", "🗂️", f.oauth, "Attach Drive files as context."),
  app(
    "google-sheets",
    "Google Sheets",
    "Productivity",
    "📊",
    f.oauth,
    "Read and write rows automatically.",
  ),
  app(
    "google-docs",
    "Google Docs",
    "Productivity",
    "📝",
    f.oauth,
    "Draft documents straight into Docs.",
  ),
  app("youtube", "YouTube", "Media", "▶️", f.key, "Summarise videos and publish uploads."),
  app(
    "whatsapp",
    "WhatsApp Business",
    "Communication",
    "💬",
    f.token,
    "Answer customers in WhatsApp threads.",
  ),
  app("telegram", "Telegram", "Communication", "✈️", f.token, "Run a bot that replies for you."),
  app("slack", "Slack", "Communication", "💼", f.oauth, "Post updates and answer in channels."),
  app("discord", "Discord", "Communication", "🎮", f.token, "Community bot with your knowledge."),
  app("x", "X (Twitter)", "Social", "𝕏", f.keySecret, "Draft, schedule and reply to posts."),
  app("facebook", "Facebook", "Social", "📘", f.oauth, "Publish posts and reply to comments."),
  app("instagram", "Instagram", "Social", "📸", f.oauth, "Auto-reply to DMs and comments."),
  app("linkedin", "LinkedIn", "Social", "🔗", f.oauth, "Write and publish professional posts."),
  app("tiktok", "TikTok", "Social", "🎵", f.oauth, "Schedule clips and read comments."),
  app("pinterest", "Pinterest", "Social", "📌", f.oauth, "Create pins from generated images."),
  app("reddit", "Reddit", "Social", "👽", f.oauth, "Monitor and answer relevant threads."),
  app("notion", "Notion", "Productivity", "📓", f.token, "Sync notes, docs and databases."),
  app("airtable", "Airtable", "Productivity", "🧱", f.key, "Read and update bases."),
  app("trello", "Trello", "Productivity", "🗃️", f.key, "Create and move cards."),
  app("asana", "Asana", "Productivity", "✅", f.token, "Create and complete tasks."),
  app("jira", "Jira", "Engineering", "🧭", f.token, "File and triage issues."),
  app("linear", "Linear", "Engineering", "📐", f.key, "Turn requests into issues."),
  app("github", "GitHub", "Engineering", "🐙", f.token, "Push generated code to a repo."),
  app("gitlab", "GitLab", "Engineering", "🦊", f.token, "Sync repos and pipelines."),
  app("bitbucket", "Bitbucket", "Engineering", "🪣", f.token, "Sync repos and pull requests."),
  app("vercel", "Vercel", "Deploy", "▲", f.token, "Deploy the app you just built."),
  app("netlify", "Netlify", "Deploy", "🌐", f.token, "One-click hosting for your build."),
  app("cloudflare", "Cloudflare", "Deploy", "🛡️", f.key, "DNS, caching and workers."),
  app("aws", "AWS", "Cloud", "☁️", f.keySecret, "S3, Lambda and more."),
  app("azure", "Azure", "Cloud", "🔷", f.key, "Cloud storage and functions."),
  app("gcp", "Google Cloud", "Cloud", "🌥️", f.key, "Buckets, functions and BigQuery."),
  app("supabase", "Supabase", "Database", "⚡", f.key, "Store every project, chat and file."),
  app(
    "postgres",
    "PostgreSQL",
    "Database",
    "🐘",
    ["Connection string"],
    "Query your own database.",
  ),
  app("mysql", "MySQL", "Database", "🐬", ["Connection string"], "Query your own database."),
  app("mongodb", "MongoDB", "Database", "🍃", ["Connection string"], "Document storage for apps."),
  app("redis", "Redis", "Database", "🧠", ["Connection string"], "Fast caching for your apps."),
  app("firebase", "Firebase", "Database", "🔥", f.key, "Realtime data and auth."),
  app("stripe", "Stripe", "Payments", "💳", f.key, "Charge customers inside your app."),
  app("paypal", "PayPal", "Payments", "🅿️", f.keySecret, "Accept payments and refunds."),
  app("razorpay", "Razorpay", "Payments", "💠", f.keySecret, "Payments for India."),
  app("paddle", "Paddle", "Payments", "🏓", f.key, "Merchant of record billing."),
  app("shopify", "Shopify", "Commerce", "🛍️", f.token, "Products, orders and support replies."),
  app("woocommerce", "WooCommerce", "Commerce", "🛒", f.keySecret, "Sync your WordPress store."),
  app("amazon-seller", "Amazon Seller", "Commerce", "📦", f.key, "Track orders and answer buyers."),
  app("etsy", "Etsy", "Commerce", "🧶", f.key, "Listings and buyer messages."),
  app("hubspot", "HubSpot", "CRM", "🧲", f.key, "Create and enrich contacts."),
  app("salesforce", "Salesforce", "CRM", "☁️", f.oauth, "Leads, deals and notes."),
  app("pipedrive", "Pipedrive", "CRM", "🚀", f.key, "Move deals automatically."),
  app("zoho", "Zoho", "CRM", "🅾️", f.key, "CRM and mail suite."),
  app("intercom", "Intercom", "Support", "💡", f.token, "Answer live chats for you."),
  app("zendesk", "Zendesk", "Support", "🎫", f.key, "Draft and resolve tickets."),
  app("freshdesk", "Freshdesk", "Support", "🍀", f.key, "Ticket triage and replies."),
  app("crisp", "Crisp", "Support", "🌊", f.key, "Website chat replies."),
  app("twilio", "Twilio", "Communication", "📱", f.keySecret, "Send SMS and calls."),
  app("sendgrid", "SendGrid", "Communication", "📤", f.key, "Bulk transactional email."),
  app("resend", "Resend", "Communication", "📧", f.key, "Beautiful product email."),
  app("mailchimp", "Mailchimp", "Marketing", "🐵", f.key, "Campaigns written by AI."),
  app("klaviyo", "Klaviyo", "Marketing", "📈", f.key, "Ecommerce flows and segments."),
  app("hootsuite", "Hootsuite", "Marketing", "🦉", f.oauth, "Schedule across every network."),
  app("buffer", "Buffer", "Marketing", "🧃", f.token, "Queue generated posts."),
  app("canva", "Canva", "Design", "🎨", f.oauth, "Export decks and graphics."),
  app("figma", "Figma", "Design", "🧩", f.token, "Turn frames into code."),
  app("unsplash", "Unsplash", "Media", "🖼️", f.key, "Free photos for slides and sites."),
  app("pexels", "Pexels", "Media", "📷", f.key, "Stock imagery and video."),
  app("elevenlabs", "ElevenLabs", "Media", "🔊", f.key, "Natural voice for your assistant."),
  app("spotify", "Spotify", "Media", "🎧", f.oauth, "Playlists and podcast data."),
  app("zoom", "Zoom", "Meetings", "🎥", f.oauth, "Schedule and summarise meetings."),
  app("google-meet", "Google Meet", "Meetings", "📹", f.oauth, "Create meetings from chat."),
  app("teams", "Microsoft Teams", "Communication", "🟣", f.oauth, "Post and reply in Teams."),
  app("outlook", "Outlook", "Communication", "📬", f.oauth, "Mail and calendar automation."),
  app("onedrive", "OneDrive", "Storage", "🗄️", f.oauth, "Attach files as context."),
  app("dropbox", "Dropbox", "Storage", "📁", f.oauth, "Sync project assets."),
  app("box", "Box", "Storage", "📦", f.oauth, "Enterprise file storage."),
  app("s3", "Amazon S3", "Storage", "🪣", f.keySecret, "Object storage for uploads."),
  app("calendly", "Calendly", "Productivity", "⏰", f.key, "Book meetings from a chat."),
  app("clickup", "ClickUp", "Productivity", "🎯", f.key, "Tasks and docs."),
  app("monday", "Monday.com", "Productivity", "🗓️", f.key, "Boards and automations."),
  app("zapier", "Zapier", "Automation", "⚙️", f.webhook, "Trigger thousands of extra apps."),
  app("make", "Make", "Automation", "🧷", f.webhook, "Visual scenarios from your AI."),
  app("n8n", "n8n", "Automation", "🕸️", f.webhook, "Self-hosted workflow runs."),
  app("ifttt", "IFTTT", "Automation", "🔁", f.webhook, "Simple trigger and action recipes."),
  app("posthog", "PostHog", "Analytics", "🦔", f.key, "Product analytics for your app."),
  app("mixpanel", "Mixpanel", "Analytics", "📶", f.key, "Track user behaviour."),
  app(
    "google-analytics",
    "Google Analytics",
    "Analytics",
    "📉",
    f.oauth,
    "Traffic reports in plain English.",
  ),
  app("sentry", "Sentry", "Engineering", "🚨", f.token, "Catch and explain errors."),
  app("openweather", "OpenWeather", "Data", "🌤️", f.key, "Live weather for assistants."),
  app("news-api", "News API", "Data", "🗞️", f.key, "Live headlines in answers."),
  app("wolfram", "Wolfram Alpha", "Data", "🧮", f.key, "Exact maths and science."),
  app("maps", "Google Maps", "Data", "🗺️", f.key, "Places, routes and distances."),
];

export const CONNECTOR_CATEGORIES = Array.from(new Set(CONNECTORS.map((c) => c.category))).sort();
