/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAgentRouteImport } from './routes/app.agent'
import { Route as AppBuildRouteImport } from './routes/app.build'
import { Route as AppBusinessRouteImport } from './routes/app.business'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppCodingRouteImport } from './routes/app.coding'
import { Route as AppConnectionsRouteImport } from './routes/app.connections'
import { Route as AppDatabaseRouteImport } from './routes/app.database'
import { Route as AppPresentationsRouteImport } from './routes/app.presentations'
import { Route as AppResearchRouteImport } from './routes/app.research'
import { Route as AppVoiceRouteImport } from './routes/app.voice'
import { Route as ShareProjectIdRouteImport } from './routes/share.$projectId'
import { Route as AppProjectProjectIdRouteImport } from './routes/app.project.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildRoute = AppBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessRoute = AppBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCodingRoute = AppCodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppDatabaseRoute = AppDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AppRoute,
} as any)
const AppPresentationsRoute = AppPresentationsRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const ShareProjectIdRoute = ShareProjectIdRouteImport.update({
  id: '/share/$projectId',
  path: '/share/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectProjectIdRoute = AppProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/ai': typeof ApiAiRoute
  '/api/search': typeof ApiSearchRoute
  '/app/agent': typeof AppAgentRoute
  '/app/build': typeof AppBuildRoute
  '/app/business': typeof AppBusinessRoute
  '/app/chat': typeof AppChatRoute
  '/app/coding': typeof AppCodingRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/database': typeof AppDatabaseRoute
  '/app/presentations': typeof AppPresentationsRoute
  '/app/research': typeof AppResearchRoute
  '/app/voice': typeof AppVoiceRoute
  '/share/$projectId': typeof ShareProjectIdRoute
  '/app/': typeof AppIndexRoute
  '/app/project/$projectId': typeof AppProjectProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ai': typeof ApiAiRoute
  '/api/search': typeof ApiSearchRoute
  '/app/agent': typeof AppAgentRoute
  '/app/build': typeof AppBuildRoute
  '/app/business': typeof AppBusinessRoute
  '/app/chat': typeof AppChatRoute
  '/app/coding': typeof AppCodingRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/database': typeof AppDatabaseRoute
  '/app/presentations': typeof AppPresentationsRoute
  '/app/research': typeof AppResearchRoute
  '/app/voice': typeof AppVoiceRoute
  '/share/$projectId': typeof ShareProjectIdRoute
  '/app': typeof AppIndexRoute
  '/app/project/$projectId': typeof AppProjectProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/ai': typeof ApiAiRoute
  '/api/search': typeof ApiSearchRoute
  '/app/agent': typeof AppAgentRoute
  '/app/build': typeof AppBuildRoute
  '/app/business': typeof AppBusinessRoute
  '/app/chat': typeof AppChatRoute
  '/app/coding': typeof AppCodingRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/database': typeof AppDatabaseRoute
  '/app/presentations': typeof AppPresentationsRoute
  '/app/research': typeof AppResearchRoute
  '/app/voice': typeof AppVoiceRoute
  '/share/$projectId': typeof ShareProjectIdRoute
  '/app/': typeof AppIndexRoute
  '/app/project/$projectId': typeof AppProjectProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/ai'
    | '/api/search'
    | '/app/agent'
    | '/app/build'
    | '/app/business'
    | '/app/chat'
    | '/app/coding'
    | '/app/connections'
    | '/app/database'
    | '/app/presentations'
    | '/app/research'
    | '/app/voice'
    | '/share/$projectId'
    | '/app/'
    | '/app/project/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/ai'
    | '/api/search'
    | '/app/agent'
    | '/app/build'
    | '/app/business'
    | '/app/chat'
    | '/app/coding'
    | '/app/connections'
    | '/app/database'
    | '/app/presentations'
    | '/app/research'
    | '/app/voice'
    | '/share/$projectId'
    | '/app'
    | '/app/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/ai'
    | '/api/search'
    | '/app/agent'
    | '/app/build'
    | '/app/business'
    | '/app/chat'
    | '/app/coding'
    | '/app/connections'
    | '/app/database'
    | '/app/presentations'
    | '/app/research'
    | '/app/voice'
    | '/share/$projectId'
    | '/app/'
    | '/app/project/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiAiRoute: typeof ApiAiRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ShareProjectIdRoute: typeof ShareProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/build': {
      id: '/app/build'
      path: '/build'
      fullPath: '/app/build'
      preLoaderRoute: typeof AppBuildRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/business': {
      id: '/app/business'
      path: '/business'
      fullPath: '/app/business'
      preLoaderRoute: typeof AppBusinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coding': {
      id: '/app/coding'
      path: '/coding'
      fullPath: '/app/coding'
      preLoaderRoute: typeof AppCodingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connections': {
      id: '/app/connections'
      path: '/connections'
      fullPath: '/app/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/database': {
      id: '/app/database'
      path: '/database'
      fullPath: '/app/database'
      preLoaderRoute: typeof AppDatabaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/presentations': {
      id: '/app/presentations'
      path: '/presentations'
      fullPath: '/app/presentations'
      preLoaderRoute: typeof AppPresentationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/research': {
      id: '/app/research'
      path: '/research'
      fullPath: '/app/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/voice': {
      id: '/app/voice'
      path: '/voice'
      fullPath: '/app/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/share/$projectId': {
      id: '/share/$projectId'
      path: '/share/$projectId'
      fullPath: '/share/$projectId'
      preLoaderRoute: typeof ShareProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/project/$projectId': {
      id: '/app/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/app/project/$projectId'
      preLoaderRoute: typeof AppProjectProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppBuildRoute: typeof AppBuildRoute
  AppBusinessRoute: typeof AppBusinessRoute
  AppChatRoute: typeof AppChatRoute
  AppCodingRoute: typeof AppCodingRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppDatabaseRoute: typeof AppDatabaseRoute
  AppPresentationsRoute: typeof AppPresentationsRoute
  AppResearchRoute: typeof AppResearchRoute
  AppVoiceRoute: typeof AppVoiceRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectProjectIdRoute: typeof AppProjectProjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppBuildRoute: AppBuildRoute,
  AppBusinessRoute: AppBusinessRoute,
  AppChatRoute: AppChatRoute,
  AppCodingRoute: AppCodingRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppDatabaseRoute: AppDatabaseRoute,
  AppPresentationsRoute: AppPresentationsRoute,
  AppResearchRoute: AppResearchRoute,
  AppVoiceRoute: AppVoiceRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectProjectIdRoute: AppProjectProjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiAiRoute: ApiAiRoute,
  ApiSearchRoute: ApiSearchRoute,
  ShareProjectIdRoute: ShareProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
