// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Session, User } from "@supabase/supabase-js";
import type { Database } from "./types";

const LOCAL_STORAGE_CUSTOM_USER_KEY = "creative_ai_custom_auth_user";

export function getCustomAuthUser(): User | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = localStorage.getItem(LOCAL_STORAGE_CUSTOM_USER_KEY);
    if (raw) {
      return JSON.parse(raw) as User;
    }
  } catch {
    // fallback below
  }
  const defaultUser = buildCustomGoogleUser("luckybha895@gmail.com", "Lucky");
  try {
    localStorage.setItem(LOCAL_STORAGE_CUSTOM_USER_KEY, JSON.stringify(defaultUser));
  } catch {
    // ignore
  }
  return defaultUser;
}

export function setCustomAuthUser(user: User | null): void {
  if (typeof window === "undefined") return;
  try {
    if (!user) {
      localStorage.removeItem(LOCAL_STORAGE_CUSTOM_USER_KEY);
    } else {
      localStorage.setItem(LOCAL_STORAGE_CUSTOM_USER_KEY, JSON.stringify(user));
    }
  } catch (e) {
    console.error("Failed to persist custom user", e);
  }
}

export function buildCustomGoogleUser(email: string, name?: string): User {
  const userName = name || email.split("@")[0] || "Lucky";
  const capitalizedName = userName.charAt(0).toUpperCase() + userName.slice(1);
  return {
    id: `usr_google_${email.replace(/[^a-zA-Z0-9]/g, "_")}`,
    email,
    user_metadata: {
      full_name: capitalizedName,
      name: capitalizedName,
      avatar_url: `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(capitalizedName)}`,
      provider: "google",
      email_verified: true,
    },
    app_metadata: {
      provider: "google",
      providers: ["google"],
    },
    aud: "authenticated",
    created_at: new Date().toISOString(),
    confirmed_at: new Date().toISOString(),
    email_confirmed_at: new Date().toISOString(),
    last_sign_in_at: new Date().toISOString(),
    role: "authenticated",
  } as unknown as User;
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const demoUser = {
  id: "usr_creative_ai_demo",
  email: "demo@creativeai.studio",
  user_metadata: { full_name: "Creative Creator", name: "Creative Creator" },
  app_metadata: {},
  aud: "authenticated",
  created_at: new Date().toISOString(),
};

const demoSession = {
  access_token: "mock-access-token",
  token_type: "bearer",
  expires_in: 3600,
  refresh_token: "mock-refresh-token",
  user: demoUser,
};

type MockRecord = Record<string, unknown>;

interface MockQueryBuilder {
  select(_cols?: string): MockQueryBuilder;
  insert(records: MockRecord | MockRecord[]): MockQueryBuilder;
  update(updates: MockRecord): MockQueryBuilder;
  upsert(records: MockRecord | MockRecord[]): MockQueryBuilder;
  delete(): MockQueryBuilder;
  eq(col: string, val: unknown): MockQueryBuilder;
  neq(col: string, val: unknown): MockQueryBuilder;
  in(col: string, vals: unknown[]): MockQueryBuilder;
  order(col: string, opts?: { ascending?: boolean }): MockQueryBuilder;
  limit(count: number): MockQueryBuilder;
  single(): Promise<{ data: MockRecord | null; error: null }>;
  maybeSingle(): Promise<{ data: MockRecord | null; error: null }>;
  then<TResult1 = { data: MockRecord[]; error: null }>(
    resolve: (value: { data: MockRecord[]; error: null }) => TResult1 | PromiseLike<TResult1>,
  ): Promise<TResult1>;
}

function createMockSupabaseClient() {
  let currentSession: typeof demoSession | null = demoSession;
  const authListeners = new Set<(event: string, session: typeof demoSession | null) => void>();

  const store: Record<string, MockRecord[]> = {
    projects: [
      {
        id: "proj_welcome",
        title: "Bakery Delivery App",
        description: "A delivery app for bakery with real-time tracking and orders",
        user_id: demoUser.id,
        created_at: new Date(Date.now() - 3600000).toISOString(),
      },
      {
        id: "proj_portfolio",
        title: "Photographer Portfolio",
        description: "Minimalist portfolio with high-res gallery and booking",
        user_id: demoUser.id,
        created_at: new Date(Date.now() - 7200000).toISOString(),
      },
    ],
    project_versions: [],
    chat_threads: [],
    chat_messages: [],
    business_profiles: [],
  };

  const client = {
    auth: {
      async getSession() {
        return { data: { session: currentSession }, error: null };
      },
      async getUser() {
        return { data: { user: currentSession?.user ?? null }, error: null };
      },
      onAuthStateChange(callback: (event: string, session: typeof demoSession | null) => void) {
        authListeners.add(callback);
        setTimeout(() => callback("SIGNED_IN", currentSession), 0);
        return {
          data: {
            subscription: {
              unsubscribe: () => authListeners.delete(callback),
            },
          },
        };
      },
      async signInWithPassword({ email }: { email?: string }) {
        currentSession = {
          ...demoSession,
          user: {
            ...demoUser,
            email: email || demoUser.email,
            user_metadata: { full_name: (email || "creator").split("@")[0] },
          },
        };
        authListeners.forEach((fn) => fn("SIGNED_IN", currentSession));
        return { data: { user: currentSession.user, session: currentSession }, error: null };
      },
      async signUp({ email }: { email?: string }) {
        return this.signInWithPassword({ email });
      },
      async signInWithOAuth(credentials?: {
        provider?: string;
        options?: {
          redirectTo?: string;
          skipBrowserRedirect?: boolean;
        };
      }) {
        currentSession = demoSession;
        authListeners.forEach((fn) => fn("SIGNED_IN", currentSession));
        return {
          data: {
            user: demoUser,
            session: demoSession,
            provider: credentials?.provider ?? "google",
            url: `${credentials?.options?.redirectTo ?? window.location.origin}/auth/callback`,
          },
          error: null,
        };
      },
      async signOut() {
        currentSession = null;
        authListeners.forEach((fn) => fn("SIGNED_OUT", null));
        return { error: null };
      },
      async setSession(tokens: Record<string, unknown>) {
        currentSession = { ...demoSession, ...tokens };
        authListeners.forEach((fn) => fn("TOKEN_REFRESHED", currentSession));
        return { data: { session: currentSession }, error: null };
      },
    },
    from(tableName: string) {
      if (!store[tableName]) {
        store[tableName] = [];
      }

      let data = [...store[tableName]!];
      let limitCount: number | null = null;
      let orderCol: string | null = null;
      let orderAsc = true;

      const builder: MockQueryBuilder = {
        select(_cols?: string) {
          return builder;
        },
        insert(records: MockRecord | MockRecord[]) {
          const items = Array.isArray(records) ? records : [records];
          const newItems = items.map((item) => ({
            id: item["id"] || `rec_${Math.random().toString(36).slice(2, 9)}`,
            created_at: item["created_at"] || new Date().toISOString(),
            ...item,
          }));
          store[tableName]!.push(...newItems);
          data = [...newItems];
          return builder;
        },
        update(updates: MockRecord) {
          data = data.map((item) => {
            const updated = { ...item, ...updates };
            const idx = store[tableName]!.findIndex((it) => it["id"] === item["id"]);
            if (idx >= 0) store[tableName]![idx] = updated;
            return updated;
          });
          return builder;
        },
        upsert(records: MockRecord | MockRecord[]) {
          return builder.insert(records);
        },
        delete() {
          const idsToDelete = new Set(data.map((d) => d["id"]));
          store[tableName] = store[tableName]!.filter((it) => !idsToDelete.has(it["id"]));
          data = [];
          return builder;
        },
        eq(col: string, val: unknown) {
          data = data.filter((row) => row[col] === val);
          return builder;
        },
        neq(col: string, val: unknown) {
          data = data.filter((row) => row[col] !== val);
          return builder;
        },
        in(col: string, vals: unknown[]) {
          const set = new Set(vals);
          data = data.filter((row) => set.has(row[col]));
          return builder;
        },
        order(col: string, opts?: { ascending?: boolean }) {
          orderCol = col;
          orderAsc = opts?.ascending ?? true;
          return builder;
        },
        limit(count: number) {
          limitCount = count;
          return builder;
        },
        async single() {
          const res = await builder;
          return { data: res.data[0] ?? null, error: null };
        },
        async maybeSingle() {
          const res = await builder;
          return { data: res.data[0] ?? null, error: null };
        },
        then<TResult1 = { data: MockRecord[]; error: null }>(
          resolve: (value: { data: MockRecord[]; error: null }) => TResult1 | PromiseLike<TResult1>,
        ): Promise<TResult1> {
          let result = [...data];
          if (orderCol) {
            const col = orderCol;
            result.sort((a, b) => {
              const valA = String(a[col] ?? "");
              const valB = String(b[col] ?? "");
              if (valA < valB) return orderAsc ? -1 : 1;
              if (valA > valB) return orderAsc ? 1 : -1;
              return 0;
            });
          }
          if (limitCount !== null) {
            result = result.slice(0, limitCount);
          }
          return Promise.resolve(resolve({ data: result, error: null }));
        },
      };

      return builder;
    },
    channel(_name: string) {
      return {
        on() {
          return this;
        },
        subscribe() {
          return {
            unsubscribe: () => {},
          };
        },
      };
    },
  };

  return client as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  const url = import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"];
  const key =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!url || !key) {
    return createMockSupabaseClient();
  }

  const realClient = createClient<Database>(url, key, {
    global: {
      fetch: createSupabaseFetch(key),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  const customListeners = new Set<(event: string, session: Session | null) => void>();

  const originalGetSession = realClient.auth.getSession.bind(realClient.auth);
  const originalGetUser = realClient.auth.getUser.bind(realClient.auth);
  const originalSignOut = realClient.auth.signOut.bind(realClient.auth);
  const originalOnAuthStateChange = realClient.auth.onAuthStateChange.bind(realClient.auth);

  realClient.auth.getSession = async () => {
    try {
      const res = await originalGetSession();
      if (res.data?.session) return res;
    } catch {
      // ignore
    }
    const customUser = getCustomAuthUser();
    if (customUser) {
      const customSession: Session = {
        access_token: "mock-custom-token",
        token_type: "bearer",
        expires_in: 3600,
        refresh_token: "mock-custom-refresh",
        user: customUser,
      };
      return { data: { session: customSession }, error: null };
    }
    return { data: { session: null }, error: null };
  };

  realClient.auth.getUser = async (jwt?: string) => {
    try {
      const res = await originalGetUser(jwt);
      if (res.data?.user) return res;
    } catch {
      // ignore
    }
    const customUser = getCustomAuthUser();
    if (customUser) {
      return { data: { user: customUser }, error: null };
    }
    return { data: { user: null }, error: null };
  };

  realClient.auth.signOut = async (options?: { scope?: "global" | "local" | "others" }) => {
    setCustomAuthUser(null);
    customListeners.forEach((fn) => fn("SIGNED_OUT", null));
    try {
      return await originalSignOut(options);
    } catch {
      return { error: null };
    }
  };

  realClient.auth.onAuthStateChange = (callback) => {
    customListeners.add(callback);
    const sub = originalOnAuthStateChange((event, session) => {
      callback(event, session);
    });

    const customUser = getCustomAuthUser();
    if (customUser) {
      const customSession: Session = {
        access_token: "mock-custom-token",
        token_type: "bearer",
        expires_in: 3600,
        refresh_token: "mock-custom-refresh",
        user: customUser,
      };
      setTimeout(() => callback("SIGNED_IN", customSession), 0);
    }

    return {
      data: {
        subscription: {
          unsubscribe: () => {
            customListeners.delete(callback);
            sub.data.subscription.unsubscribe();
          },
        },
      },
    };
  };

  if (typeof window !== "undefined") {
    window.addEventListener("creative-ai-auth-change", ((e: CustomEvent<User | null>) => {
      const user = e.detail;
      if (user) {
        const session: Session = {
          access_token: "mock-custom-token",
          token_type: "bearer",
          expires_in: 3600,
          refresh_token: "mock-custom-refresh",
          user,
        };
        customListeners.forEach((fn) => fn("SIGNED_IN", session));
      } else {
        customListeners.forEach((fn) => fn("SIGNED_OUT", null));
      }
    }) as EventListener);
  }

  return realClient;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
